baseURL = "https://yangtudou.github.io"

# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true

# 网站标题
title = "洋san芋suo"




# 是否使用 robots.txt
enableRobotsTXT = true

# 是否使用 emoji 代码
enableEmoji = true

# 主题
theme = "DoIt"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  # DoIt 主题版本
  version = "0.2.15"
  defaultTheme = "auto"
  
  [params.footer]
    enable = true
    custom = ''
    hugo = false
    hostedOn = '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>'
    copyright = true
    author = false
    since = 2020
    icp = ""
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = true
    lightgallery = true
    ruby = true
    # DoIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = false
    # DoIt 新增 | 0.2.14 配置文章原始文件的链接
    linkToSource = false
    # "https://github.com/user/repo/blob/main/{path}"
    # DoIt 新增 | 0.2.13 配置编辑文章的链接
    linkToEdit = false
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
    # DoIt 新增 | 0.2.14 配置提交错误的链接
    linkToReport = false
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    # DoIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # DoIt 新增 | 0.2.13 是否在文章开头显示系列导航
    seriesNavigation = true
    # 是否启用最后修改时间
    enableLastMod = false
    # 是否启用字数统计
    enableWordCount = false
    # 是否启用阅读时间估计
    enableReadingTime = false
    # DoIt 新增 | 0.2.13 过时文章提示
    [params.page.outdatedArticleReminder]
      enable = true
      # 如果文章最后更新于 90 天之前，显示提醒
      reminder = 90
      # 如果文章最后更新于 180 天之前，显示警告
      warning = 180
    # DoIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = true
      # 是否使侧边目录自动折叠展开
      auto = true
    # DoIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 默认展开显示的代码行数
      maxShownLines = 10
      # 是否显示代码行号
      lineNos = false
      # 是否开启代码换行
      wrap = false
      # 是否显示代码块标题
      header = true
    # DoIt 新增 | 0.2.14 表格配置
    [params.page.table]
      # 是否开启表格排序
      sort = true
    # DoIt 更改 | 0.2.0 KaTeX 数学公式
    [params.page.math]
      enable = true
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = false
      # KaTeX 插件 mhchem
      mhchem = false
      # 使用 MathJax 替代 KaTeX
      mathjax = false
    # DoIt 新增 | 0.2.0 Mapbox GL JS 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true




[menu]
  [[menu.main]]
    identifier = "fish-memory"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    post = ""
    name = "鱼的记忆"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "ME"
    url = "/about/"
    title = ""
    weight = 2

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
